# theme: jekyll-theme-minimal

title: "Przemysław Majdański"
description: "Starting each new day with new technology and a problem that I see for the first time in my eyes, enjoying learning new solutions, not afraid to make mistakes, ruthless to my monitor if the problem still appears on 235 lines of code."

github_username: codeforinfra-przemek

remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

theme: jekyll-theme-modernist
